### ISSUE TITLE
Show property other than real time users?

### ISSUE THREAD

**Issue by mhdfaran** [captain-melanie/stream-deck-google-analytics#2]
I really like your work this code is work like a charm. I was wondering if we can show other properties also like conversion? I am no good coder if you could help me which file or code i need to edit to show conversion property i would very appreciate that. Thank you :)

**Comment by captain-melanie** [comment]
<del>Hi, unfortunately this plugin uses [Google Analytics API V3](https://developers.google.com/analytics/devguides/reporting/realtime/dimsmets/user) which only provides one metric -- activeUsers </del>

<del>This plugin needs to be updated to use [V4](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema#metrics) in order to make use of all the metrics listed here:[ API Dimensions & Metrics](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema#metrics)</del>

Actually, v3 provides a few more numeric properties: total events, specific goal conversions, and total goal conversions. I've added them to the new version.

**Comment by captain-melanie** [comment]
Hi, I've upgraded the plugin to include [more properties](https://github.com/captain-melanie/stream-deck-google-analytics#features), you could find the new version here https://github.com/captain-melanie/stream-deck-google-analytics/tree/master/Release

The goal conversion property is looking good to me. Let me know if you have any questions. 
(In case if you want to find the old version, you could do `git checkout 15f4b02e1c3dda55bf34a89596595e6790e8a471`)

![image](https://user-images.githubusercontent.com/20979257/119294069-a306b300-bc21-11eb-89e0-b5b98f7c2378.png)

**Comment by mhdfaran** [comment]
Thank you so much brother i will check and let you know. You are the best 🙏

**Comment by mhdfaran** [comment]
It's working, thank you. I don't know if i am asking for too much but
everytime i open the stream deck i have to put all the information again in
settings. Is there any chance that we save data to it so we don't have to
put data everytime we open it. One more thing I was thinking is if we could
use it in multiple buttons like 1 button shows active users other button
shows conversion at the same time.

**Comment by captain-melanie** [comment]
Oh, no worries, this sounds an improvement to the plugin. I found entering data every time annoying too. 
>  there any chance that we save data to it so we don't have to
put data everytime we open it.

There is a `SetSettings` function provided by Stream Deck to save settings. I'll look into it to see how to integrate. 

> multiple buttons like 1 button shows active users other button shows conversion at the same time.

This feature sounds useful too. I would need to dig further how to work with multiple buttons. Will keep you updated

**Comment by mhdfaran** [comment]
Thank you. I am also wondering if we could use other properties besides
real time like Total number of users today and total number of conversions
today

**Comment by captain-melanie** [comment]
Hi, [Google Real-time API ](https://developers.google.com/analytics/devguides/reporting/realtime/dimsmets)doesn't include these metrics, I think it is because these metrics are not considered as real-time, they are rather report data, so I'm a bit reluctant to add them into the plugin (since the plugin is named GA Real-time)

**Comment by mhdfaran** [comment]
Oh i see. No problem brother :)
